# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_logging', map(lambda str: "../src/" + str,
                            ["LogRecord.cc"
#                             "Component.cc",
#                             "Trace.cc",
#                             "Log.cc",
#                             "LogFormatter.cc",
#                             "LogDestination.cc",
#                             "DualLog.cc",
#                             "ScreenLog.cc"
                            ]), LIBS=env.getlibs("boost utils daf_base pex_exceptions"))

