# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_logging', map(lambda str: "../src/" + str,
                            ["LogRecord.cc",
                             "PropertyPrinter.cc",
                             "LogFormatter.cc",
                             "LogDestination.cc",
#                             "Trace.cc",
                             "Component.cc",
                             "Log.cc",
                             "ScreenLog.cc",
                             "DualLog.cc"
                            ]), LIBS=env.getlibs("boost utils daf_base pex_exceptions"))

