# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['blockTimingLog',
                                  'common/common',
                                  'debug',
                                  'log/log',
                                  'logRecord/logRecord',
                                  'screenLog',
                                  'threshold',
                                  'trace'], addUnderscore=False)
